version: '3'

services:
  db:
    image: postgres:10.6
    container_name: clean_db
  redis:
    image: redis
    ports:
      - 6379:6379
  web:
    build: .
    image: rails_cleaning_companies/web
    container_name: clean-web
    command: bash -c "puma"
    depends_on:
      - db
      - redis
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - /app/node_modules

